apiVersion: batch/v1
kind: Job
metadata:
  name: calcuagvtwo-job
spec:
  template:
    spec:
      containers:
      - name: calcuagvtwo-job
        image: yash5090/calcuagvtwo:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
